name: schedule
on:
  schedule:
    - cron: "0 1 * * *"  # 每天 09:00 北京时间 ≈ 01:00 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: hotspot-mapper/0.1 by actions
        run: |
          python -m src.main
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/
