name: schedule
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: hotspot-mapper/0.1 by actions
          FEISHU_BOT_SECRET: ${{ secrets.FEISHU_BOT_SECRET }}
        run: |
          python -m src.main
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: outputs
          path: outputs/
